### ISSUE TITLE
Resolve References using Style Dictionary

### ISSUE THREAD

**Issue by allindeveloper** [lukasoppermann/design-token-transformer#27]
Hello there, Thanks for this Great Library

Please any idea of how to resolve references ?
```
{
    "global": {
      "hello-pink": {
        "50": {
          "value": "#fge7ee",
          "type": "color"
        },
      },
      "white": {
        "value": "#ffffff",
        "type": "color"
      }
    },
    "Light": {
      "bg": {
        "default": {
          "value": "{white}",
          "type": "color",
          "description": "Default background color for the whole app."
        },
      },
      }
    }
  }
```

Here is the error i get
```js
scss

Property Reference Errors:
Reference doesn't exist: Light.bg.default.value tries to reference white, which is not defined
```

**Comment by lukasoppermann** [comment]
Hey, this is an issue you are having with style dictionary, not really the plugin.

I think the issue is that you need to use `{global.white}`

**Comment by allindevelopergig** [comment]
Got it..
I opened another issue there... I don't mind if you can help too
https://github.com/amzn/style-dictionary/issues/830

**Comment by allindeveloper** [comment]
> Hey @allindeveloper did you try to use `{global.white}`?

`global.white` would work but it wont work in using figma token plugin.. i believe, the designer uses the plugin

**Comment by allindevelopergig** [comment]
so from here https://github.com/amzn/style-dictionary/issues/830
`global.accent.default` would work but the issue is, `accent.default` has to be within the same token file not in a different global file...
And I think it's best to follow what's coming from figma and the plugin...

**Comment by lukasoppermann** [comment]
So @allindeveloper did this solve your problem?

**Comment by allindevelopergig** [comment]
I had to do `{dark.accent.default}` and `{light.accent.default}` which solved my issue
Thank you
