### ISSUE TITLE
Transform-tokens workflow always creates the file design-tokens-example.tokens.json

### ISSUE THREAD

**Issue by benjamindburke** [lukasoppermann/design-token-transformer#30]
The transform-tokens workflow has a hardcoded value for the file name: https://github.com/lukasoppermann/design-token-transformer/blob/5db78c72e55312c577341da27faac2d0b60225fd/.github/workflows/transform-tokens.yml#L28

The action should use the filename from the client_payload object:

```yml
name: ${{ github.event.client_payload.filename }}
```

I'd open a PR to fix this myself, but I don't have permissions.

**Comment by lukasoppermann** [comment]
Hey, we once had the option to allow user to specify a name, but that was somehow added work.

I am happy to accept a pr. However, this means we need to add it to the payload in the main plugin.

You should be able to send PRs to both repos. Other people can send PRs as well.

**Comment by benjamindburke** [comment]
Thanks for confirming. I don't often contribute to OSS so I was unfamiliar with opening a PR from a fork. But I figured it out! #31 addresses this issue
