### ISSUE TITLE
Unit transforms don't seem to apply

### ISSUE THREAD

**Issue by mwargan** [lukasoppermann/design-token-transformer#4]
Hi!

It seems units aren't being added as expected. As an example, the build/scss file uses the transformGroup SCSS https://amzn.github.io/style-dictionary/#/transform_groups?id=scss, which includes size/rem, which in turn should append the unit `rem` to relevant variables, but it doesn't seem to be doing that.

**Comment by lukasoppermann** [comment]
Hey @mwargan this is easy to fix by using custom conversions. I updated this package to use the transfomers for px and percent.
