### ISSUE TITLE
rgba values becomes #0000000

### ISSUE THREAD

**Issue by djalmaaraujo** [lukasoppermann/design-token-transformer#44]
When I run with values like the image:

<img width="427" alt="image" src="https://user-images.githubusercontent.com/3402/213777940-ab521633-2a86-438b-b32d-db52c8ad053b.png">

The output json becomes like this:

<img width="348" alt="image" src="https://user-images.githubusercontent.com/3402/213777991-06838c7d-933b-486d-8957-d521e8146314.png">

Is this a known issue? Any ideas on how to fix?

**Comment by lukasoppermann** [comment]
Did you find the problem yourself?
