### ISSUE TITLE
Unable to receive the commit message in GitHub's pull request.

### ISSUE THREAD

**Issue by hayawata3626** [lukasoppermann/design-token-transformer#50]
I have forked this repository for my use.
I want to receive the commit message in GitHub's pull request.

Although I have commit messages, the commit message in GitHub's pull request always appears as "Tokens updated."
I understand the cause. refer: https://github.com/lukasoppermann/design-token-transformer/blob/main/.github/workflows/transform-tokens.yml#L46

I would like to set the commit message in the following section if a commit message is received through the request body.
Like this.

```yaml
commit-message: ${{ github.event.client_payload.commitMessage || 'Tokens updated' }}
```

## The setting

<img width="640" alt="スクリーンショット 2023-08-18 11 28 03" src="https://github.com/lukasoppermann/design-token-transformer/assets/15213369/762dbb7b-d17e-4019-b628-077074ed3a32">

**Comment by hayawata3626** [comment]
Added the [PR](https://github.com/lukasoppermann/design-token-transformer/pull/51).

**Comment by hayawata3626** [comment]
@lukasoppermann 
I'm not completely understanding, but what does "Merged" mean? 
My own [PR](https://github.com/lukasoppermann/design-token-transformer/pull/51) hasn't been merged yet.
If I miss something, sorry.

**Comment by lukasoppermann** [comment]
Sorry I am on the go and had internet trouble apparently. Now it should be merged.

**Comment by hayawata3626** [comment]
Thank you!
