### ISSUE TITLE
Style Dictionary 4 

### ISSUE THREAD

**Issue by jkinley** [lukasoppermann/design-token-transformer#53]
Hi Lukas, just wondering if you aware that the folks from Figma have seemed to join forces with Danny Banks to work on v4. Looks like some good progress is being made. Anyway, if you are not involved, thought you might be interested. It seems to me that some of your work with your transformer could be used in the W3C compatibility aspects that they plan to bake in. Here are some links:

- https://tokens-studio.slack.com/archives/C0622L9CKDM
- https://github.com/orgs/amzn/projects/4/views/1?layout=board

**Comment by lukasoppermann** [comment]
Hey, I think these are the folks from token studio, not figma, right? I am aware of this happening but not involved. I have a lot of stuff going on as it is. 😅 

Do you have a specific issue you feel is about the w3c compatability?
