### ISSUE TITLE
Some units are called "pixel" while others are called "pixels"

### ISSUE THREAD

**Issue by mwargan** [lukasoppermann/design-token-transformer#6]
Suggested to either keep consistent naming, or modify `transformTokens.js` line 9 to read     `return (token.unit === 'pixel' || token.unit === 'pixels') && token.value !== 0`

**Comment by lukasoppermann** [comment]
Hey @mwargan thanks for raising this. Can you let me know which units are called 'pixels'? I have a hard time finding it in the code base. Thanks.

**Comment by mwargan** [comment]
@lukasoppermann so far for me only `lineHeight` has been plural.

**Comment by lukasoppermann** [comment]
Hey @mwargan this should be fixed in the latest plugin release.
